### ISSUE TITLE
New release for scikit-learn installation

### ISSUE THREAD

**Issue by tomityrrell** [karolzak/boxdetect#25]
Hello maintainers,

I saw there was a commit recently to replace sklearn with scikit-learn in the repository's requirements, as the former is now deprecated.  Will there be a new release (1.0.1?) that includes this change?

Thanks,

Tomi

**Comment by karolzak** [comment]
Hi @tomityrrell !
Yeah it makes perfect sense to drop a new release. Thanks!

**Comment by josephcxhxa** [comment]
Hi @karolzak 

Version 1.0.1 keeps installing me sklearn instead of scikit-learn.

![image](https://user-images.githubusercontent.com/54529065/213050570-5fd3c015-cf3b-420b-a6a7-d0edb4c146fb.png)

Maybe it should be also updated in setup.py ([https://github.com/karolzak/boxdetect/blob/master/setup.py#L33](https://github.com/karolzak/boxdetect/blob/master/setup.py#L33))

**Comment by josephcxhxa** [comment]
And also update from sklearn to scikit-learn in code like here:
[https://github.com/karolzak/boxdetect/blob/master/boxdetect/config.py#L7](https://github.com/karolzak/boxdetect/blob/master/boxdetect/config.py#L7)

**Comment by karolzak** [comment]
@josephcxhxa it absolutely should have been updated!
Thanks for the heads up - will fix right away and bump version again
