### ISSUE TITLE
Failure in UnitTests

### ISSUE THREAD

**Issue by josephcxhxa** [karolzak/boxdetect#28]
Hi!

Been having this issue for a while. Aaside from an extra warning log while running and while running my unit tests, I always got this warning but no major issues locally and with my company Jenkins job.

![image](https://user-images.githubusercontent.com/54529065/213269764-73216086-e695-4bb7-a89b-21228e085112.png)
![image](https://user-images.githubusercontent.com/54529065/213270938-c9b99200-6032-4df0-aefa-f351386c42d7.png)

But recently my Jenkins job started to reject me those tests, so I tested it downloading boxdetect, adding the recomendation from the first image and now everything is working fine!

![image](https://user-images.githubusercontent.com/54529065/213270749-12ec1d53-dfef-496e-8dcf-59a647ab6883.png)
![image](https://user-images.githubusercontent.com/54529065/213271010-74f54701-d6ef-47d8-bead-e28464ddeb10.png)

 (The failed test has nothing to do with boxdetect hehe)

**Comment by karolzak** [comment]
Wow, thank you so much @josephcxhxa 
You just saved me what could have been hours of scratching my head and investigating the root cause.
I noticed that my unit tests started failing after recent update from `sklearn`->`scikit-learn` and I was afraid that I will need to make some major changes in the code but it seems like I just had to put `dtype=object` in 2 places and that solved the issue.
Thank you! I now pushed these updates and everything should be working correct in v1.0.2 release
